### ISSUE TITLE
win11 24H2 环境下无响应

### ISSUE THREAD

**Issue by bingsunny0730** [Scanood/onemouse#1]
点了exe程序无反应，以管理员身份运行也是，是需要安装依赖环境吗？还是未适配？另外包也有点大了。。

**Comment by mppon** [comment]
> 点了exe程序无反应，以管理员身份运行也是，是需要安装依赖环境吗？还是未适配？另外包也有点大了。。

你好，预编译的程序我在win10，win11，ubuntu测试都可以打开，暂不清楚你的原因，你可以尝试用源代码自行编译。
