### ISSUE TITLE
远程控制点击服务端的onemouse程序的最小化、最大化和关闭按钮都会卡柱。

### ISSUE THREAD

**Issue by guoxu-github** [Scanood/onemouse#2]

**Comment by guoxu-github** [comment]
win11版本

**Comment by mppon** [comment]
你好，请问你使用的是否是从releases中下载的，可以尝试通过源代码进行编译，因为releases不是最新的。当前的逻辑点击服务端的关闭按钮，程序就会退出了，最大化的功能目前是被禁用的，至于最小化卡住的问题，可否提供更多的信息，比如视频等，感谢。

**Comment by guoxu-github** [comment]
https://github.com/user-attachments/assets/6b793c6d-b8b0-4e44-807c-695d5b46d0a0

点击最小化时，就会卡住，然后被控端点击一下鼠标就又好了。感觉点了最小化之后鼠标事件就被阻止了。我debuff了一下。发现是nutjs的pressButton的promise的状态不会改变了。不知道是为啥

**Comment by guoxu-github** [comment]
我是直接拉的代码跑起来的。被控端是build生成的

**Comment by mppon** [comment]
原因暂不清楚，通过自定义窗口标题栏可以解决，代码已上传。
